### PR TITLE
.htaccess verbietet den Download der woff, woff2 und js.map files

### PR DESCRIPTION
**Pull request by rrusch**

### CODE REVIEW

**Review by OpenXE-ERP — CHANGES_REQUESTED** [review]
'woff' files will be removed soon, can you please remove the woffs from the commit and only leave 'js.map'?

**Comment by rrusch** [comment]
Ok, no problem.

**Comment by rrusch** [comment]
Actually there is a check if the `.htaccess` files in / and /www have a certain content. This is done by a `strcmp()`. I really don't know the reason behind this, but I'm also updating the function.

**Comment by rrusch** [comment]
Found another forbidden file: `www/js/production/generic/web/locale/locale.properties`
This prevents the viewer from appearing in the correct language.

**Comment by OpenXE-ERP** [comment]
It is probably best to reorganize the folders some time. All insecure / non-problematic content should reside in a public folder. I am moving this to a new issue and merge the pull request.

**Review by OpenXE-ERP — APPROVED** [review]

**Comment by Diralytic** [comment]
woff2 fehlt

**Pull request merged**
