### PR TITLE
Basic Sendcloud integration with Shipment rework

### PR DESCRIPTION
**Pull request by exciler**
While working on the Sendcloud integration I discovered that the whole module "versandarten" should be reworked and a proper interface or base class for "versanddienstleister" should be developed.

The current code is a first "it works" implementation that has more room for improvements and cleanup but I wanted to share the current state for discussion and input.

CAN be merged I think, but can also be postponed until further improvements are done.

### CODE REVIEW

**Comment by exciler** [comment]
This is linked to #23

**Comment by OpenXE-ERP** [comment]
Thanks for the contribution, looks like quite a big rework. I am absolutely positive about how you put it in separate files and cleaned erpapi.

Should we maintain it as a separate branch, until further testing is done?

**Comment by exciler** [comment]
That is a really good question. I have no clue if the existing "versandarten" are working at all and if yes to which degree. Intraship and the old DHL integration will probably no longer work because the APIs have changed.
Do you have any information about this? The question for me is: How much can we break? ;-)

**Comment by OpenXE-ERP** [comment]
Maybe it's a good idea to rework the versandarten system, but focus only on some selected services (DHL, UPS, sendcloud).

I'll try to start some poll thread on openxe.org

**Comment by michel42-1** [comment]
+ DHL Express would be nice

**Comment by OpenXE-ERP** [comment]
UPS for us

**Comment by exciler** [comment]
> UPS for us

Are you currently using any UPS integration in OpenXE/Xentral OSS or in Xentral Enterprise?
Would shipping with UPS via Sendcloud be an (intermediate) option?

**Comment by exciler** [comment]
> * DHL Express would be nice

Shipping with DHL Express via Sendcloud should be possible right away... would that be an (intermediate) option for you?

**Comment by michel42-1** [comment]
not really, native is better, we have good conditions by DHL Express because we also make a lot of import with them.

**Comment by michel42-1** [comment]
we still use DHL Express in Xentral Enterprise and it works, but because API's will change, we will go to openxe

**Comment by OpenXE-ERP** [comment]
> > UPS for us
> 
> Are you currently using any UPS integration in OpenXE/Xentral OSS or in Xentral Enterprise? Would shipping with UPS via Sendcloud be an (intermediate) option?

Xentral Enterprise 20, but UPS is not used right now because the system is firewalled in. We do want to use UPS native with openxe after the migration (Dez 22/Jan 23)

**Comment by exciler** [comment]
> not really, native is better, we have good conditions by DHL Express because we also make a lot of import with them.

Of course native is better and a native module will be created over time. I just want to see how to assign priority to all those things.
You can use Sendcloud with your own conditions and you will be billed by DHL (or UPS or whatever) as normally. Sendcloud will just charge a little on top for their service. With implementing a single API we can cover DHL/DHLExpress/UPS/DPD/GLS and many more really quick. This is why I started with Sendcloud.

**Comment by michel42-1** [comment]
ok, looks maybe interesting then also for us, I'll check. I understand, that sendcloud will make it much easier because just one API for all services. I agree, sendcloud will be most urgent now

**Comment by OpenXE-ERP** [comment]
I tried your implementation, but there was an error when going to the edit action. Can you check it?

Cannot assign null to property Versanddienstleister::$settings of type object/var/www/html/OpenXE_exciler/www/lib/class.versanddienstleister.php:26
--
Versanddienstleister→__construct()/var/www/html/OpenXE_exciler/www/lib/versandarten/sendcloud.php:206Versandart_sendcloud→__construct()/var/www/html/OpenXE_exciler/www/pages/versandarten.php:7855Versandarten→loadModule()/var/www/html/OpenXE_exciler/www/pages/versandarten.php:2214Versandarten→VersandartenEdit()/var/www/html/OpenXE_exciler/phpwf/class.application.php:2343Application→ActionHandlerListen()/var/www/html/OpenXE_exciler/www/pages/versandarten.php:572Versandarten→__construct()/var/www/html/OpenXE_exciler/phpwf/class.player.php:2681Player→Run()/var/www/html/OpenXE_exciler/www/index.php:62 | 7Versanddienstleister→__construct()/var/www/html/OpenXE_exciler/www/lib/versandarten/sendcloud.php:20 | 6Versandart_sendcloud→__construct()/var/www/html/OpenXE_exciler/www/pages/versandarten.php:785 | 5Versandarten→loadModule()/var/www/html/OpenXE_exciler/www/pages/versandarten.php:221 | 4Versandarten→VersandartenEdit()/var/www/html/OpenXE_exciler/phpwf/class.application.php:234 | 3Application→ActionHandlerListen()/var/www/html/OpenXE_exciler/www/pages/versandarten.php:57 | 2Versandarten→__construct()/var/www/html/OpenXE_exciler/phpwf/class.player.php:268 | 1Player→Run()/var/www/html/OpenXE_exciler/www/index.php:62
7Versanddienstleister→__construct()/var/www/html/OpenXE_exciler/www/lib/versandarten/sendcloud.php:20
6Versandart_sendcloud→__construct()/var/www/html/OpenXE_exciler/www/pages/versandarten.php:785
5Versandarten→loadModule()/var/www/html/OpenXE_exciler/www/pages/versandarten.php:221
4Versandarten→VersandartenEdit()/var/www/html/OpenXE_exciler/phpwf/class.application.php:234
3Application→ActionHandlerListen()/var/www/html/OpenXE_exciler/www/pages/versandarten.php:57
2Versandarten→__construct()/var/www/html/OpenXE_exciler/phpwf/class.player.php:268
1Player→Run()/var/www/html/OpenXE_exciler/www/index.php:62

Cannot assign null to property Versanddienstleister::$settings of type object
[/var/www/html/OpenXE_exciler/www/lib/class.versanddienstleister.php:26](editor://open?file=/var/www/html/OpenXE_exciler/www/lib/class.versanddienstleister.php&line=26)
7Versanddienstleister→__construct()
[/var/www/html/OpenXE_exciler/www/lib/versandarten/sendcloud.php:20](editor://open?file=%2Fvar%2Fwww%2Fhtml%2FOpenXE_exciler%2Fwww%2Flib%2Fversandarten%2Fsendcloud.php&line=20)
6Versandart_sendcloud→__construct()
[/var/www/html/OpenXE_exciler/www/pages/versandarten.php:785](editor://open?file=%2Fvar%2Fwww%2Fhtml%2FOpenXE_exciler%2Fwww%2Fpages%2Fversandarten.php&line=785)
5Versandarten→loadModule()
[/var/www/html/OpenXE_exciler/www/pages/versandarten.php:221](editor://open?file=%2Fvar%2Fwww%2Fhtml%2FOpenXE_exciler%2Fwww%2Fpages%2Fversandarten.php&line=221)
4Versandarten→VersandartenEdit()
[/var/www/html/OpenXE_exciler/phpwf/class.application.php:234](editor://open?file=%2Fvar%2Fwww%2Fhtml%2FOpenXE_exciler%2Fphpwf%2Fclass.application.php&line=234)
3Application→ActionHandlerListen()
[/var/www/html/OpenXE_exciler/www/pages/versandarten.php:57](editor://open?file=%2Fvar%2Fwww%2Fhtml%2FOpenXE_exciler%2Fwww%2Fpages%2Fversandarten.php&line=57)
2Versandarten→__construct()
[/var/www/html/OpenXE_exciler/phpwf/class.player.php:268](editor://open?file=%2Fvar%2Fwww%2Fhtml%2FOpenXE_exciler%2Fphpwf%2Fclass.player.php&line=268)
1Player→Run()
[/var/www/html/OpenXE_exciler/www/index.php:62](editor://open?file=%2Fvar%2Fwww%2Fhtml%2FOpenXE_exciler%2Fwww%2Findex.php&line=62)

**Comment by OpenXE-ERP** [comment]
> I tried your implementation, but there was an error when going to the edit action. Can you check it?
> ## Cannot assign null to property Versanddienstleister::$settings of type object/var/www/html/OpenXE_exciler/www/lib/class.versanddienstleister.php:26

Solution: Initialize 'einstellungen_json' with '{}':
```

$this->app->DB->Insert(
        "INSERT INTO `versandarten` 
              (`bezeichnung`, `type`,`aktiv`, `geloescht`, `modul`,`ausprojekt`, `versandmail`, `einstellungen_json`) 
            VALUES ('$name','$type','1','0','$shippingMethodModule','0', $versandmail,'')"
```

```
$this->app->DB->Insert(
        "INSERT INTO `versandarten` 
              (`bezeichnung`, `type`,`aktiv`, `geloescht`, `modul`,`ausprojekt`, `versandmail`, `einstellungen_json`) 
            VALUES ('$name','$type','1','0','$shippingMethodModule','0', $versandmail,'{}')"
```

**Comment by exciler** [comment]
Damn, I had already fixed that but did not add that change to my commit :-/
Should be fixed now...

**Comment by OpenXE-ERP** [comment]
Next error:

When saving the edit mask and something is in the "private_key" input:

array_map(): Argument #2 ($array) must be of type array, stdClass given
[/var/www/html/OpenXE_exciler/classes/Carrier/SendCloud/SendCloudApi.php:63](editor://open?file=/var/www/html/OpenXE_exciler/classes/Carrier/SendCloud/SendCloudApi.php&line=63)

**Comment by exciler** [comment]
That is probably because you entered an "invalid" key. Did not yet implement a proper error handling in case the API calls fail.
I have focused on the label creating which works fine for me now.
I will implement the error handling next.

**Comment by OpenXE-ERP** [comment]
I suggest to pull your modifications into a seperate development branch to add more services and for further testing. What do you think?

**Comment by exciler** [comment]
That is fine for me, but I am not sure who will test a different branch. For me, the integration is working now and it would be good to get some feedback from other users as well.
Adding more services from my side will take a litte bit, because I need the "Abolauf" Module working first. After that I can hopefully "switch" my Xentral OSS to OpenXE and concentrate on new features again.

**Comment by OpenXE-ERP** [comment]
Is it possible to use the old interfaces in parallel to your implementation?

**Comment by exciler** [comment]
No, not right away.
But for me the main question is: Is any of the old "Versanddienstleister" actually working? Intraship is no longer available by DHL, Internetmarke did not work for me. As DHL versenden has been replaced in the non-OSS version of Xentral with a newer version, I doubt it will work any good.
That was the main reason I left behind all the old code. If any of those is working for you, I can probably move them to the new interface quickly. If I have to create them from scratch it will take a little bit of time.

**Comment by OpenXE-ERP** [comment]
Ok, then I suggest we merge after the next release (production module). I will try to do testing on sendcloud as well. We should implement DHL 3.3 and UPS as soon as possible after that.

**Comment by exciler** [comment]
That seems very a good suggestion.
I will try to implement DHL next, because I am familiar with an earlier version of DHL API.
For UPS I have no experience at all and no account. Maybe someone can provide some information about the UPS API (Link to Documentation, Testing environments).

**Comment by OpenXE-ERP** [comment]
We are UPS customer, I can provide information and/or help to implement the UPS interface.

**Comment by exciler** [comment]
Just a quick update: DHL Integration for "Paket National" is working in an early stage. Additional services are still missing...

**Comment by exciler** [comment]
Summary: I just merged the current master into my branch and added 3 bugfix commits (575ab86, b14265b, 88eb175)

**Pull request merged**
